### ISSUE TITLE
Use <select> element inside VaSelect component

### ISSUE THREAD

**Issue by SamuelRiversMoore** [nvms/vue-atlas#13]
The VaSelect component doesn't have any `<select>` input inside it.
This is not only problematic for form serialization, but also for the use of VaSelect on phone or tablets since this devices manage selection with a special dedicated responsive menu.

**Comment by nvms** [comment]
I'm playing around with the idea of embedding a hidden <select> element into the VaSelect component. The element would have its value bound to the value of the component. I realize that this wouldn't solve the mobility issue, but at this point I'm considering the ability to serialize the component a bigger problem. I'll get something figured out for this soon.

As far as the mobility issues, and allowing the devices to handle the VaSelect how they would normally handle a <select>, I'm wondering if we'd be able to trigger and open the hidden <select> when the VaSelect is triggered, change its **visibility** property to 'visible', while placing it far enough off canvas that it is not seen by the user. I'm not quite sure about this yet. I'll keep thinking.

**Comment by SamuelRiversMoore** [comment]
Why not simply use a styled `<select>` box with VaButton's css?
I understand you want to use a VaButton inside the VaSelect to keep the same logic everywhere but in this case it doesn't help us much... :-)

**Comment by nvms** [comment]
This would break a lot of other functionality, like the ability to filter using a search, add new items, use a customer render format, etc., unless the component was entirely re-written to accommodate for this change. That's obviously an option, but I'm wondering if it would not be prudent to simply introduce a new component (e.g. VaSingleSelect) that would just be `<select>` element under the hood while following the design principal that's already in place.


Or.. rename VaSelect to VaMultiSelect, and introduce a VaSingleSelect, with the caveat that VaMultiSelect doesn't comply with FormData while VaSingleSelect does. However, VaMultiSelect could still be serialized using other methods, since its v-model is just an array of strings. Throwing that into some payload is trivial.


What do you think?

**Comment by nvms** [comment]
unlikely this will happen without somebody submitting a PR for it. the current implementation makes it easy enough to iterate over using the VaSelect's v-model.
