### ISSUE TITLE
active=false buttons still clicks

### ISSUE THREAD

**Issue by max-frai** [nvms/vue-atlas#61]
`<va-button :active="false" @click.native="doSomething">Text</va-button>`

When button is not active, click handler still works. This force to write additional check in click handler which makes code complicate. Is it the problem with active or with handling?

**Comment by nvms** [comment]
the `active` prop is to show, visually, that the button is doing something, e.g. for when it is used as the Select component's trigger, or a dropdown element's trigger. it should still be clickable when active is true.

to prevent clicking or pressing enter to trigger the button you would want to use the `disabled` prop.

`<va-button disabled @click="doSomething">text</va-button>`

...this issue has made me realize that the disabled prop is broken. I'm fixing this right now and will push another quick release, because that is definitely important. opening a separate issue for that. thank you

**Comment by nvms** [comment]
the `disabled` prop was fixed in #63, and the documentation page has been updated to include an example of what I believe you are trying to accomplish
