### ISSUE TITLE
DatePicker value can't be Date or null

### ISSUE THREAD

**Issue by rejifald** [nvms/vue-atlas#72]
Null value cause datepicker to set 1970 year.
Also Date object or ISO-UTC string also looks like this 
![image](https://user-images.githubusercontent.com/42000283/52963930-c50d8d00-33a9-11e9-8fb8-65045fa25d1a.png)

**Comment by nvms** [comment]
this is fixed in the two commits above.

passing `null` or an empty string to the Datepicker results in this expected behavior:
<img width="331" alt="nulloremptystring" src="https://user-images.githubusercontent.com/17074357/52970255-0b41fc80-3368-11e9-801e-6ae92668f66e.png">

passing a `Date` object should result in this expected behavior:
<img width="333" alt="date" src="https://user-images.githubusercontent.com/17074357/52970277-1e54cc80-3368-11e9-9e81-92fda81275ea.png">
