### ISSUE TITLE
FR - validation rules to be more convenient

### ISSUE THREAD

**Issue by rejifald** [nvms/vue-atlas#77]
I suggest add few props, like "required", like, 'regex', and so on.

**Comment by nvms** [comment]
one of the built-in `type`s you can pass to the `rules` prop is `required`.

from http://localhost:8080/documentation/form:

```html
<va-input
      name="name"
      v-model="demoForm.name"
      placeholder="Your name"
      :rules="[{type:'required', tip:'Sorry, I need to know your name'}]"
      clearable />
```

is this what you're looking for?

I do like the idea of being able to pass your own regular expressions to the `rules` prop. I will explore that possibility.

**Comment by rejifald** [comment]
No, i mean something like 
```
<va-input
      name="name"
      v-model="demoForm.name"
      placeholder="Your name"
      :required="true"
      tip="Sorry, I need to know your name"
      error="name shouldn't contain numbers"
      clearable />
```

**Comment by rejifald** [comment]
It's just like native required

**Comment by nvms** [comment]
ah, I see. very possible. I'll work on this.

**Comment by rejifald** [comment]
I thing something like this
```
<va-input
  name="email"
  v-model="demoForm.email"
  placeholder="Your email address"
  required="true"
  type="email"
  min="2"
  max="10"
  clearable />
```

Main idea is more clear and native component description. Instead of creating additional array for almost every input. And it looks too heavy in template, but add this array in data also will be heavy. So my data function will be too large.

**Comment by rejifald** [comment]
BTW, i need add.
min and max depend on input type.
So string type will be checked by it length property, and number type by it's value.
It's convenient, but it also maybe confusing... I am not sure, is it ok. WDYT ?

**Comment by nvms** [comment]
I agree that this may become confusing for the different components that inherit validation properties. this could also prove as a limitation in future components that may inherit validation properties, such as the Range component that already has a min and max prop, which would conflict with the proposed solution above. it should always be very clear what the min and max props do, and they should always do the same thing. it is always best to be explicit rather than implicit.

with that said, I think I would like to stick with the current implementation.

I still like the idea of being able to pass custom expressions along with a rule, but may take it a bit further by allowing a method to be passed instead of just an expression. in this method you could do whatever testing you want, returning true for success or false for error... or something along those lines.

I'm going to close this issue, but will open a new one regarding the proposed custom rules solution.

**Comment by rejifald** [comment]
Yes, maybe custom validation error message parser will be helpful, to change default error text

**Comment by rejifald** [comment]
And about min and max, essentially, it does one thing. Number, String, Range, TextArea, all of them can have min and max. Difference is, which property they limit.
For custom components this behavior is ok. 
It’s just may be confusing in case if someone will try set them to native html elements.
